project:
  type: website
  output-dir: docs/

website:
  title: "Interactive Online Companionship (IOC)"
  navbar:
    left:
      - href: index.qmd
        text: Inscription
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



