project:
  type: website
  output-dir: docs/

website:
  title: "InforBio"
  navbar:
    left:
      - href: index.qmd
        text: About US
      - ioc_info.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



